name: Release

on:
  push:
    branches: ["main"]
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v6
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Build release
        run: composer run-script build

      - name: Version
        id: version
        run: |-
          echo PASS2CF_VERSION="$(composer run-script version)" \
            >> "$GITHUB_OUTPUT"
          git log $(git describe --tags --abbrev=0)..HEAD --oneline \
            > changes.txt

      - uses: ncipollo/release-action@bcfe5470707e8832e12347755757cec0eb3c22af # v1.18.0
        with:
          artifactContentType: "application/zip"
          artifactErrorsFailBuild: true
          artifacts: "pass2cf.zip"
          bodyFile: changes.txt
          draft: true
          omitDraftDuringUpdate: true
          removeArtifacts: true
          tag: "v${{ steps.version.outputs.PASS2CF_VERSION }}"
          updateOnlyUnreleased: true
