name: WordPress Plugin

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

permissions:
  contents: read

jobs:
  yaml-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ibiqlik/action-yamllint@v3
        with:
          config_data: |-
            extends: default
            rules:
              document-start:
                present: false
              truthy:
                check-keys: false
            ignore:
              - node_modules
              - vendor

  php-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: overtrue/phplint@9.1.2

  composer-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: test ! -f composer.json || composer validate --strict

  wordpress-phpunit:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Run tests
        id: test
        uses: holyhope/test-wordpress-plugin-github-action@v2.0.4
        with:
          phpunit_version: ""
          plugin_slug: pass2cf

      - uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: ${{ steps.test.outputs.junit_report }}

  language-files-up-to-date:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: holyhope/install-wp-cli-github-action@v1.0.0
        id: wp-cli
      - name: Check language files
        shell: bash
        run: |-
          generated_pot="$(mktemp --tmpdir="$RUNNER_TEMP" pass2cf.XXXXXX.pot)"
          committed_pot="$(mktemp --tmpdir="$RUNNER_TEMP" committed.XXXXXX.pot)"
          normalized_pot="$(
            mktemp --tmpdir="$RUNNER_TEMP" normalized.XXXXXX.pot
          )"
          unique_messages="$(mktemp --tmpdir="$RUNNER_TEMP" unique.XXXXXX.po)"

          '${{ steps.wp-cli.outputs.path }}' i18n make-pot \
            . \
            "$generated_pot" \
            --slug=pass2cf \
            --exclude=.github,vendor

          sed -E \
            -e '/^# Copyright/d' \
            -e '/^#:/d' \
            -e '/^"POT-Creation-Date:/d' \
            -e '/^"X-Generator:/d' \
            languages/pass2cf.pot \
            > "$committed_pot"
          sed -E \
            -e '/^# Copyright/d' \
            -e '/^#:/d' \
            -e '/^"POT-Creation-Date:/d' \
            -e '/^"X-Generator:/d' \
            "$generated_pot" \
            > "$normalized_pot"

          diff --unified "$committed_pot" "$normalized_pot"

          msgcomm \
            --unique \
            --omit-header \
            --no-location \
            languages/pass2cf-fr_FR.po \
            "$generated_pot" \
            > "$unique_messages"

          if test -s "$unique_messages"; then
            cat "$unique_messages"
            exit 1
          fi
